// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF5DlJk-SZp7pv9H0vKcekkeTY928XjJU',
    appId: '1:881049663435:web:75ec1a23e5c5bc5958e84e',
    messagingSenderId: '881049663435',
    projectId: 'digitutor-b5d93',
    authDomain: 'digitutor-b5d93.firebaseapp.com',
    storageBucket: 'digitutor-b5d93.appspot.com',
    measurementId: 'G-QDTGYN25GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4sR4ZKdG8HvpX36l-ZbWED9SPE6aBi9M',
    appId: '1:881049663435:android:c07486ec493acf4658e84e',
    messagingSenderId: '881049663435',
    projectId: 'digitutor-b5d93',
    storageBucket: 'digitutor-b5d93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP1z-islI5_B2To6dFGg-mguXWwtSXUHs',
    appId: '1:881049663435:ios:79398eacfa9f0a8d58e84e',
    messagingSenderId: '881049663435',
    projectId: 'digitutor-b5d93',
    storageBucket: 'digitutor-b5d93.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP1z-islI5_B2To6dFGg-mguXWwtSXUHs',
    appId: '1:881049663435:ios:79398eacfa9f0a8d58e84e',
    messagingSenderId: '881049663435',
    projectId: 'digitutor-b5d93',
    storageBucket: 'digitutor-b5d93.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF5DlJk-SZp7pv9H0vKcekkeTY928XjJU',
    appId: '1:881049663435:web:5b264ddd3ebab8c758e84e',
    messagingSenderId: '881049663435',
    projectId: 'digitutor-b5d93',
    authDomain: 'digitutor-b5d93.firebaseapp.com',
    storageBucket: 'digitutor-b5d93.appspot.com',
    measurementId: 'G-Q9GPVQ9KYX',
  );
}
