import 'package:google_fonts/google_fonts.dart';
bool mode = true;
bool notification = true;
String langTitle = 'العربية';
String appBarLogo = "Assets/appBarLogo.png";
String? jwt = '';
String? role = '';
late double screenHeight;
late double screenWidth;
var font= GoogleFonts.changa();
